[package]
authors = ["Wez Furlong"]
name = "termwiz"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = "~0.9"
bitflags = "~1.0"
cassowary = "~0.3"
derive_builder = "~0.5"
failure = "~0.1"
fnv = "~1.0"
image = "~0.19"
libc = "~0.2"
memmem = "~0.1"
num = "~0.2"
num-traits = "~0.2"
ordered-float = "~0.5"
palette = "~0.4"
regex = "~0.2"
semver = "0.9"
serde = {version="~1.0", features = ["rc"]}
serde_derive = "~1.0"
smallvec = "~0.6"
terminfo = "~0.6"
unicode-segmentation = "~1.2"
unicode-width = "~0.1"

# https://github.com/jwilm/vte/pull/20
vte = { git = "https://github.com/wez/vte", branch="oscbigbuf" }

[dev-dependencies]
bincode = "1.1"

[dependencies.num-derive]
features = ["full-syntax"]
version = "~0.2"
[target."cfg(unix)".dependencies]
signal-hook = "~0.1"
termios = "~0.3"
[target."cfg(windows)".dependencies.winapi]
features = [
    "winbase",
    "winerror",
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "synchapi",
]
version = "~0.3"
